### ISSUE TITLE
<HTML> syntax should be supported

### ISSUE THREAD

**Issue by splitbrain** [saggi-dw/dokuwiki-plugin-htmlok#1]
Basically the same as the existing code but with a different `getPType()`

**Comment by saggi-dw** [comment]
I have [added ](https://github.com/saggi-dw/dokuwiki-plugin-htmlok/commit/e3bc31cba9dc25b095f0afc18d5e362a6a80f516)`<HTML>` with the `PType block`. I hope I have understood this correctly. I'm not very familiar with GIT or PHP and hope I'm not creating too much nonsense.

**Comment by mkrischer** [comment]
also <html></html> . plugin works with uppercase, before the upgrade it works with upper and lowercase <html> tags

**Comment by mkrischer** [comment]
this one works as expected: http://dokuwiki.org/plugin:htmlokalt

**Comment by saggi-dw** [comment]
The plugin works with lowercase and uppercase letters for the tags. See also [#4](https://github.com/saggi-dw/dokuwiki-plugin-htmlok/issues/4#issuecomment-1511563438) or https://www.dokuwiki.org/plugin:htmlok#syntax
If there is a problem with correct execution: please explain the exact details that cause the problem.

**Comment by saggi-dw** [comment]
> this one works as expected: http://dokuwiki.org/plugin:htmlokalt

Please note: A simultaneously installed [confightmlok](https://www.dokuwiki.org/plugin:confightmlok) ([htmlokalt](https://www.dokuwiki.org/plugin:htmlokalt)) with disabled processing leads to the source code and not the result is displayed!

The documentation with reference to the conflict was adjusted.
