### ISSUE TITLE
htmlok config unnecessary? 

### ISSUE THREAD

**Issue by splitbrain** [saggi-dw/dokuwiki-plugin-htmlok#2]
Having an additional config option to enable the  plugin when there is already a way to enable/disable the plugin itself seems a bit silly?

**Comment by saggi-dw** [comment]
Yes, of course. However, the explicit enable should be an additional indication of the security risk. Too much?

**Comment by splitbrain** [comment]
:man_shrugging: No idea. People will shoot their feet anyway. Feel free to close this.

**Comment by Klap-in** [comment]
I see there is now also option for php, so there is choice.

**Comment by Klap-in** [comment]
My understanding is that enabling is allowing to execute? If not enabled, this plugin will only display, say it is another syntax for a code block?

**Comment by saggi-dw** [comment]
> My understanding is that enabling is allowing to execute? If not enabled, this plugin will only display, say it is another syntax for a code block?

In principle, yes. The idea is to copy the behavior before the current release "Jack Jackrum".
`**Please Note**: HTML and PHP embedding is disabled by default in the configuration. If disabled, the code is displayed instead of executed.`

**Comment by saggi-dw** [comment]
> I see there is now also option for php, so there is choice.

Good point, then I close this.
